### ISSUE TITLE
readLines breaks if file's first line is larger than the chunk_size

### ISSUE THREAD

**Issue by stu-blair** [anpur/line-navigator#10]
Not sure if this is a bug or a necessary constraint, but if you call `readLines` on a file with a first line longer than the chunk size, you get an error like this:
`Line 0 is out of index, last available: none`

I understand chunk size is configurable, but ideally LineNavigator could handle files with long lines while reading in chunks smaller than those lines. 
If this is a necessary constraint (or more trouble to fix than it's worth), a more informative error message referencing the chunk size limitation would save users some time when they run into this issue.

(Thanks so much for this library by the way!)

**Comment by anpur** [comment]
Thanks for reporting! This is a bug, as intention was to threat lines longer than a chunk as several lines. 
Time to fix all the issues.

**Comment by stu-blair** [comment]
Awesome, thanks @anpur !

**Comment by anpur** [comment]
Fixed this issue, now you have a choice via `options.throwOnLongLines` field to either have an error or split long lines to several.
Error message is sane too. Hope it helps.

**Comment by stu-blair** [comment]
Wow what a quick fix, thanks again!
