### ISSUE TITLE
Does not work with utf16le encoding

### ISSUE THREAD

**Issue by hansmaad** [anpur/line-navigator#9]
The following code get stuck in an infinite loop of `readSomeLines`

            var navigator = new LineNavigator(this.file, { encoding : 'utf16le' });
            navigator.readLines(10, 10, (err, index, lines: string[], isEof, progress) => {});

[testfile.txt](https://github.com/anpur/line-navigator/files/652151/testfile.txt)

**Comment by anpur** [comment]
@hansmaad Thank you for detailed bug and test data! Will try to fix it today.

**Comment by anpur** [comment]
I'd like to do small refactoring of line ending finding mechanism, to make it more clean to fix this issue, which will take more time than a day.
Meanwhile I've updated `readme.md` acknowledging not supported encoding. Sorry for inconvenience.

**Comment by anpur** [comment]
Got a chance to fix utf16le encoding
